// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Test, stdJson} from "forge-std/Test.sol";
import {SKRToken} from "../src/SKRToken.sol";
import {StakingVault} from "../src/StakingVault.sol";
import {ChallengeRegistry} from "../src/ChallengeRegistry.sol";
import {Sortition} from "../src/Sortition.sol";
import {AttestationStore} from "../src/AttestationStore.sol";
import {AttestationEngine} from "../src/AttestationEngine.sol";
import {QueryGateway} from "../src/QueryGateway.sol";
import {MathVerifierAdapter, IMathGroth16Verifier} from "../src/verifiers/MathVerifierAdapter.sol";
import {MathGroth16Verifier} from "../src/verifiers/MathVerifier.sol";

/// @title AttestationEngineReal — Gate 2: full on-chain verification of a
///        real Groth16 proof emitted by snarkjs from the math circuit.
///
/// @notice This test reads test/fixtures/calldata.json (generated by
///         circuits/scripts/prove.ts) and replays the proof through
///         AttestationEngine. The claimant address is hardcoded to
///         0x00000000000000000000000000000000000000C1 because that is the
///         address the fixture was generated for — the bindingHash baked
///         into the witness is keccak256(abi.encode(0xC1, 1)) & MASK.
contract AttestationEngineRealTest is Test {
    using stdJson for string;

    address constant CLAIMANT = address(0xC1);

    SKRToken internal token;
    StakingVault internal vault;
    ChallengeRegistry internal registry;
    Sortition internal sortition;
    AttestationStore internal store;
    AttestationEngine internal engine;
    QueryGateway internal gateway;
    MathGroth16Verifier internal mathInner;
    MathVerifierAdapter internal mathAdapter;

    address internal gov = address(0xA11CE);
    address internal proposer = address(0xB0B);

    function setUp() public {
        vm.warp(1_700_000_000);
        vm.roll(1_000);

        vm.startPrank(gov);
        token = new SKRToken(gov);
        vault = new StakingVault(token, gov);
        registry = new ChallengeRegistry(token, gov);
        sortition = new Sortition(vault);
        store = new AttestationStore(gov);
        engine = new AttestationEngine(registry, vault, sortition, store, gov);
        gateway = new QueryGateway(store);
        mathInner = new MathGroth16Verifier();
        mathAdapter = new MathVerifierAdapter(IMathGroth16Verifier(address(mathInner)));

        vault.setEngine(address(engine));
        store.setEngine(address(engine));

        // Fund proposer + a few validators (not strictly needed for Gate 2
        // but lets us exercise the full submit path)
        token.transfer(proposer, 20_000 ether);
        for (uint256 i = 0; i < 10; i++) {
            address v = address(uint160(0x4000 + i));
            token.transfer(v, 5_000 ether);
        }
        vm.stopPrank();

        for (uint256 i = 0; i < 10; i++) {
            address v = address(uint160(0x4000 + i));
            vm.startPrank(v);
            token.approve(address(vault), 5_000 ether);
            vault.bond(5_000 ether);
            vm.stopPrank();
        }

        // Propose and activate the math challenge with the REAL verifier adapter
        vm.startPrank(proposer);
        token.approve(address(registry), 10_000 ether);
        registry.propose(
            ChallengeRegistry.Domain.APPLIED_MATH,
            address(mathAdapter),
            bytes32("math-spec"),
            bytes32("math-hash"),
            1_000 ether
        );
        vm.stopPrank();
        vm.prank(gov);
        registry.activate(1);
    }

    function test_Real_mathProofVerifies() public {
        // Sanity: contract's bindingHash for this claimant must match the
        // value baked into the fixture
        uint256 expected = engine.bindingHashOf(CLAIMANT, 1);
        assertEq(
            expected,
            137113079119533894390044129544115621214479906292030050397668714953666719736,
            "bindingHash fixture drift"
        );

        string memory json = vm.readFile(
            string.concat(vm.projectRoot(), "/test/fixtures/calldata.json")
        );

        uint256[2] memory a;
        a[0] = json.readUint(".a[0]");
        a[1] = json.readUint(".a[1]");

        uint256[2][2] memory b;
        b[0][0] = json.readUint(".b[0][0]");
        b[0][1] = json.readUint(".b[0][1]");
        b[1][0] = json.readUint(".b[1][0]");
        b[1][1] = json.readUint(".b[1][1]");

        uint256[2] memory c;
        c[0] = json.readUint(".c[0]");
        c[1] = json.readUint(".c[1]");

        // circuitSignals = [base, modulus, result]
        uint256[] memory circuitSignals = json.readUintArray(".circuitSignals");
        assertEq(circuitSignals.length, 3, "expected 3 circuit signals");
        assertEq(circuitSignals[0], 2);
        assertEq(circuitSignals[1], 97);
        assertEq(circuitSignals[2], 6); // 2^20 mod 97 = 6

        // Submit the real proof via AttestationEngine → adapter → MathGroth16Verifier
        vm.prank(CLAIMANT);
        uint256 claimId = engine.submitClaim(
            1, a, b, c, circuitSignals, bytes32("real-artifact")
        );
        assertEq(claimId, 1);

        AttestationEngine.Claim memory cl = engine.getClaim(claimId);
        assertEq(uint256(cl.status), uint256(AttestationEngine.ClaimStatus.SUBMITTED));
    }
}
