/* ═══════════════════════════════════════════════════════════════
   File: src/app/submit/page.tsx
   SkillRoot — Submit Attestation Page
   ═══════════════════════════════════════════════════════════════
   Interactive glass challenge card with silk-styled form inputs.
   Framer Motion staggered entrance, glassmorphism panels,
   neon-accented submit flow with particle feedback on success.
   ═══════════════════════════════════════════════════════════════ */

'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { useWriteContract } from 'wagmi';
import { contracts } from '@/lib/contracts';
import { attestationEngineAbi } from '@/lib/abis';
import { ProofUpload, type ParsedProof } from '@/components/ProofUpload';
import { TxStatus } from '@/components/TxStatus';
import { ConnectButton } from '@/components/ConnectButton';
import Link from 'next/link';
import type { Hash } from 'viem';
import { stringToBytes, bytesToHex } from 'viem';

/* ── Framer Motion Variants ──────────────────────────────────── */
const containerVariants = {
  hidden: {},
  visible: {
    transition: { staggerChildren: 0.12, delayChildren: 0.1 },
  },
};

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: [0.25, 0.46, 0.45, 0.94] },
  },
};

/* ═══════════════════════════════════════════════════════════════ */
export default function SubmitPage() {
  const [proof, setProof] = useState<ParsedProof | null>(null);
  const [artifactCID, setArtifactCID] = useState('');
  const [challengeId, setChallengeId] = useState('1');
  const [hash, setHash] = useState<Hash | undefined>();

  const { writeContract, isPending, error } = useWriteContract();

  async function submit() {
    if (!proof) return;
    /* Pack CID as bytes32 — takes only the first 32 UTF-8 bytes */
    const cidBytes = stringToBytes(artifactCID, { size: 32 });
    const cid = bytesToHex(cidBytes);

    writeContract(
      {
        address: contracts.engine,
        abi: attestationEngineAbi,
        functionName: 'submitClaim',
        args: [
          BigInt(challengeId),
          [BigInt(proof.a[0]), BigInt(proof.a[1])],
          [
            [BigInt(proof.b[0][0]), BigInt(proof.b[0][1])],
            [BigInt(proof.b[1][0]), BigInt(proof.b[1][1])],
          ],
          [BigInt(proof.c[0]), BigInt(proof.c[1])],
          proof.circuitSignals.map((s) => BigInt(s)),
          cid as `0x${string}`,
        ],
      },
      {
        onSuccess: (h) => setHash(h),
      }
    );
  }

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="space-y-8"
    >
      {/* ── Navigation ───────────────────────────────────────── */}
      <motion.header
        variants={fadeUp}
        className="flex items-center justify-between"
      >
        <Link
          href="/"
          className="flex items-center gap-2 text-sm text-silk-dim hover:text-neon-cyan transition-colors group"
        >
          <span className="inline-block transition-transform group-hover:-translate-x-1">&larr;</span>
          <span>Home</span>
        </Link>
        <ConnectButton />
      </motion.header>

      {/* ── Page Title ───────────────────────────────────────── */}
      <motion.div variants={fadeUp} className="space-y-2">
        <h1 className="text-display-sm text-gradient">Submit Attestation</h1>
        <p className="text-sm text-silk-dim max-w-lg">
          Upload your Groth16 proof generated by <code className="font-mono text-neon-cyan/80">skr solve</code>,
          specify the challenge, and submit your claim on-chain.
        </p>
        <p className="text-xs text-silk-muted">v0.2.0-no-vote · 100 SKR bond · 24h fraud-proof window · auto-finalize if unchallenged</p>
      </motion.div>

      {/* ── Main Form Card ───────────────────────────────────── */}
      <motion.div
        variants={fadeUp}
        className="glass-card-strong p-6 sm:p-8 space-y-6 gradient-border"
      >
        {/* Challenge ID input */}
        <div className="space-y-2">
          <label className="block text-xs font-medium text-silk-muted uppercase tracking-wider">
            Challenge ID
          </label>
          <input
            type="number"
            value={challengeId}
            onChange={(e) => setChallengeId(e.target.value)}
            className="glass-input w-32 font-mono"
            min="1"
          />
        </div>

        <hr className="glass-divider" />

        {/* Proof Upload */}
        <ProofUpload onParsed={setProof} />

        <hr className="glass-divider" />

        {/* Artifact CID input */}
        <div className="space-y-2">
          <label className="block text-xs font-medium text-silk-muted uppercase tracking-wider">
            Artifact CID (IPFS)
          </label>
          <input
            type="text"
            value={artifactCID}
            onChange={(e) => setArtifactCID(e.target.value)}
            placeholder="bafkrei..."
            className="glass-input w-full font-mono"
          />
          <p className="text-2xs text-silk-faint">
            Optional. Links proof-supporting artifacts stored on IPFS.
          </p>
        </div>

        <hr className="glass-divider" />

        {/* Submit button */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 pt-2">
          <button
            onClick={submit}
            disabled={!proof || isPending}
            className="btn-primary min-w-[180px]"
          >
            {isPending ? (
              <span className="flex items-center gap-2">
                <span className="inline-block w-4 h-4 border-2 border-void/30 border-t-void rounded-full animate-spin" />
                Submitting&hellip;
              </span>
            ) : (
              'Submit Claim'
            )}
          </button>

          {/* Proof status indicator */}
          {proof && (
            <motion.span
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              className="flex items-center gap-2 text-xs text-silk-dim"
            >
              <span className="status-dot-success" />
              Proof loaded &mdash; {proof.circuitSignals.length} signal{proof.circuitSignals.length !== 1 ? 's' : ''}
            </motion.span>
          )}
        </div>

        {/* Error display */}
        {error && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-subtle p-4 border-red-500/20 border"
          >
            <div className="flex items-start gap-2">
              <span className="status-dot-error mt-1 shrink-0" />
              <p className="text-sm text-red-400 break-all">{error.message}</p>
            </div>
          </motion.div>
        )}
      </motion.div>

      {/* ── Transaction Status ───────────────────────────────── */}
      {hash && (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <TxStatus hash={hash} />
        </motion.div>
      )}

      {/* ── Help Text ────────────────────────────────────────── */}
      <motion.div variants={fadeUp}>
        <div className="glass-subtle p-5 space-y-2">
          <h3 className="text-xs font-medium text-silk-muted uppercase tracking-wider">
            How to generate a proof
          </h3>
          <div className="text-sm text-silk-dim leading-relaxed space-y-1">
            <p>
              1. Install the CLI: <code className="font-mono text-neon-cyan/80 text-xs">npm i -g @skillroot/cli</code>
            </p>
            <p>
              2. Solve the challenge: <code className="font-mono text-neon-cyan/80 text-xs">skr solve --challenge 1</code>
            </p>
            <p>
              3. Upload the generated <code className="font-mono text-neon-cyan/80 text-xs">calldata.json</code> above.
            </p>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
