#!/usr/bin/env bash
#
# deploy-sepolia.sh — deploy SkillRoot v0 to Base Sepolia.
#
# Runs Deploy.s.sol with SKIP_GOV_TRANSFER=1 so the deployer retains the
# governance role long enough to seed the initial math challenge. The
# governance handover to the Governance contract + multi-sig happens in a
# follow-up transaction (see docs/bootstrapping.md week 7–8).
#
# Environment variables required:
#   PRIVATE_KEY           - deployer private key (hex, 0x-prefixed or not)
#   RPC_URL               - Base Sepolia RPC endpoint
#
# Optional:
#   ETHERSCAN_API_KEY     - enables verification
#   MATH_VERIFIER         - pre-deployed MathVerifierAdapter address
#                           (if unset, this script skips seeding — you will
#                            need to deploy the verifier separately before
#                            seed-challenges.sh can run)
#   SPEC_CID              - bytes32 of the math challenge spec
#   CIRCUIT_HASH          - bytes32 of the math circuit r1cs hash

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
CONTRACTS="$ROOT/contracts"
DEPLOYMENTS="$ROOT/deployments"
OUT_FILE="$DEPLOYMENTS/base-sepolia.json"

: "${PRIVATE_KEY:?set PRIVATE_KEY in env}"
: "${RPC_URL:?set RPC_URL in env (Base Sepolia)}"

mkdir -p "$DEPLOYMENTS"

echo "[..] deploying to Base Sepolia via $RPC_URL"
cd "$CONTRACTS"

EXTRA_ARGS=()
if [ -n "${ETHERSCAN_API_KEY:-}" ]; then
  EXTRA_ARGS+=(--verify --etherscan-api-key "$ETHERSCAN_API_KEY")
fi

SKIP_GOV_TRANSFER=1 forge script script/Deploy.s.sol:Deploy \
  --rpc-url "$RPC_URL" \
  --broadcast \
  "${EXTRA_ARGS[@]}" \
  --json 2>&1 | tee /tmp/deploy-sepolia.log

# Extract addresses from the forge script console.log lines
extract() {
  grep -Eo "^  $1\s+0x[a-fA-F0-9]{40}" /tmp/deploy-sepolia.log | awk '{print $NF}' | tail -n1
}

TOKEN=$(extract "SKRToken")
GOVERNANCE=$(extract "Governance")
VAULT=$(extract "StakingVault")
REGISTRY=$(extract "ChallengeRegistry")
SORTITION=$(extract "Sortition")
STORE=$(extract "AttestationStore")
ENGINE=$(extract "AttestationEngine")
GATEWAY=$(extract "QueryGateway")

if [ -z "$TOKEN" ] || [ -z "$ENGINE" ]; then
  echo "[err] failed to parse deployment addresses from forge output" >&2
  echo "      see /tmp/deploy-sepolia.log" >&2
  exit 1
fi

# Write deployments/base-sepolia.json
cat > "$OUT_FILE" <<JSON
{
  "chain": "base-sepolia",
  "chainId": 84532,
  "deployedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "deployer": "$(cast wallet address --private-key "$PRIVATE_KEY" 2>/dev/null || echo 'unknown')",
  "contracts": {
    "SKRToken":          "$TOKEN",
    "Governance":        "$GOVERNANCE",
    "StakingVault":      "$VAULT",
    "ChallengeRegistry": "$REGISTRY",
    "Sortition":         "$SORTITION",
    "AttestationStore":  "$STORE",
    "AttestationEngine": "$ENGINE",
    "QueryGateway":      "$GATEWAY",
    "MathVerifier":      "${MATH_VERIFIER:-pending}"
  },
  "notes": "Governance role still held by deployer. Run bootstrapping week 7–8 handover to transfer to Governance contract."
}
JSON

echo "[ok] wrote $OUT_FILE"

# Sync to app/.env.local so the frontend picks up the addresses
APP_ENV="$ROOT/app/.env.local"
cat > "$APP_ENV" <<EOF
# Generated by scripts/deploy-sepolia.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
NEXT_PUBLIC_CHAIN_ID=84532
NEXT_PUBLIC_SKR_TOKEN=$TOKEN
NEXT_PUBLIC_GOVERNANCE=$GOVERNANCE
NEXT_PUBLIC_STAKING_VAULT=$VAULT
NEXT_PUBLIC_CHALLENGE_REGISTRY=$REGISTRY
NEXT_PUBLIC_SORTITION=$SORTITION
NEXT_PUBLIC_ATTESTATION_STORE=$STORE
NEXT_PUBLIC_ATTESTATION_ENGINE=$ENGINE
NEXT_PUBLIC_QUERY_GATEWAY=$GATEWAY
NEXT_PUBLIC_MATH_VERIFIER=${MATH_VERIFIER:-0x0000000000000000000000000000000000000000}
EOF
echo "[ok] synced addresses to $APP_ENV"

echo
echo "next steps:"
echo "  1. deploy MathVerifierAdapter: forge create src/verifiers/MathVerifierAdapter.sol:MathVerifierAdapter --rpc-url \$RPC_URL --private-key \$PRIVATE_KEY --constructor-args <MathGroth16Verifier>"
echo "  2. re-run with MATH_VERIFIER=<adapter> in env to update base-sepolia.json"
echo "  3. run ./scripts/seed-challenges.sh to propose + activate the math challenge"
